name: Eslint Check

on:
  push:
    branches:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.6
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Lint Check
        run: bun lint
